/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutSiteRouteImport } from './routes/about-site'
import { Route as CharacteristicsRouteImport } from './routes/characteristics'
import { Route as CoatRouteImport } from './routes/coat'
import { Route as CompositionRouteImport } from './routes/composition'
import { Route as ConservationRouteImport } from './routes/conservation'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GeneticsRouteImport } from './routes/genetics'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HeatRouteImport } from './routes/heat'
import { Route as IdentificationRouteImport } from './routes/identification'
import { Route as MilkRouteImport } from './routes/milk'
import { Route as MorphologyRouteImport } from './routes/morphology'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as OriginRouteImport } from './routes/origin'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as ReproductionRouteImport } from './routes/reproduction'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as TractRouteImport } from './routes/tract'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSiteRoute = AboutSiteRouteImport.update({
  id: '/about-site',
  path: '/about-site',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacteristicsRoute = CharacteristicsRouteImport.update({
  id: '/characteristics',
  path: '/characteristics',
  getParentRoute: () => rootRouteImport,
} as any)
const CoatRoute = CoatRouteImport.update({
  id: '/coat',
  path: '/coat',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositionRoute = CompositionRouteImport.update({
  id: '/composition',
  path: '/composition',
  getParentRoute: () => rootRouteImport,
} as any)
const ConservationRoute = ConservationRouteImport.update({
  id: '/conservation',
  path: '/conservation',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneticsRoute = GeneticsRouteImport.update({
  id: '/genetics',
  path: '/genetics',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatRoute = HeatRouteImport.update({
  id: '/heat',
  path: '/heat',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentificationRoute = IdentificationRouteImport.update({
  id: '/identification',
  path: '/identification',
  getParentRoute: () => rootRouteImport,
} as any)
const MilkRoute = MilkRouteImport.update({
  id: '/milk',
  path: '/milk',
  getParentRoute: () => rootRouteImport,
} as any)
const MorphologyRoute = MorphologyRouteImport.update({
  id: '/morphology',
  path: '/morphology',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginRoute = OriginRouteImport.update({
  id: '/origin',
  path: '/origin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const ReproductionRoute = ReproductionRouteImport.update({
  id: '/reproduction',
  path: '/reproduction',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const TractRoute = TractRouteImport.update({
  id: '/tract',
  path: '/tract',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-site': typeof AboutSiteRoute
  '/characteristics': typeof CharacteristicsRoute
  '/coat': typeof CoatRoute
  '/composition': typeof CompositionRoute
  '/conservation': typeof ConservationRoute
  '/editorial': typeof EditorialRoute
  '/gallery': typeof GalleryRoute
  '/genetics': typeof GeneticsRoute
  '/health': typeof HealthRoute
  '/heat': typeof HeatRoute
  '/identification': typeof IdentificationRoute
  '/milk': typeof MilkRoute
  '/morphology': typeof MorphologyRoute
  '/nutrition': typeof NutritionRoute
  '/origin': typeof OriginRoute
  '/references': typeof ReferencesRoute
  '/reproduction': typeof ReproductionRoute
  '/research': typeof ResearchRoute
  '/tract': typeof TractRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-site': typeof AboutSiteRoute
  '/characteristics': typeof CharacteristicsRoute
  '/coat': typeof CoatRoute
  '/composition': typeof CompositionRoute
  '/conservation': typeof ConservationRoute
  '/editorial': typeof EditorialRoute
  '/gallery': typeof GalleryRoute
  '/genetics': typeof GeneticsRoute
  '/health': typeof HealthRoute
  '/heat': typeof HeatRoute
  '/identification': typeof IdentificationRoute
  '/milk': typeof MilkRoute
  '/morphology': typeof MorphologyRoute
  '/nutrition': typeof NutritionRoute
  '/origin': typeof OriginRoute
  '/references': typeof ReferencesRoute
  '/reproduction': typeof ReproductionRoute
  '/research': typeof ResearchRoute
  '/tract': typeof TractRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-site': typeof AboutSiteRoute
  '/characteristics': typeof CharacteristicsRoute
  '/coat': typeof CoatRoute
  '/composition': typeof CompositionRoute
  '/conservation': typeof ConservationRoute
  '/editorial': typeof EditorialRoute
  '/gallery': typeof GalleryRoute
  '/genetics': typeof GeneticsRoute
  '/health': typeof HealthRoute
  '/heat': typeof HeatRoute
  '/identification': typeof IdentificationRoute
  '/milk': typeof MilkRoute
  '/morphology': typeof MorphologyRoute
  '/nutrition': typeof NutritionRoute
  '/origin': typeof OriginRoute
  '/references': typeof ReferencesRoute
  '/reproduction': typeof ReproductionRoute
  '/research': typeof ResearchRoute
  '/tract': typeof TractRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-site'
    | '/characteristics'
    | '/coat'
    | '/composition'
    | '/conservation'
    | '/editorial'
    | '/gallery'
    | '/genetics'
    | '/health'
    | '/heat'
    | '/identification'
    | '/milk'
    | '/morphology'
    | '/nutrition'
    | '/origin'
    | '/references'
    | '/reproduction'
    | '/research'
    | '/tract'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-site'
    | '/characteristics'
    | '/coat'
    | '/composition'
    | '/conservation'
    | '/editorial'
    | '/gallery'
    | '/genetics'
    | '/health'
    | '/heat'
    | '/identification'
    | '/milk'
    | '/morphology'
    | '/nutrition'
    | '/origin'
    | '/references'
    | '/reproduction'
    | '/research'
    | '/tract'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-site'
    | '/characteristics'
    | '/coat'
    | '/composition'
    | '/conservation'
    | '/editorial'
    | '/gallery'
    | '/genetics'
    | '/health'
    | '/heat'
    | '/identification'
    | '/milk'
    | '/morphology'
    | '/nutrition'
    | '/origin'
    | '/references'
    | '/reproduction'
    | '/research'
    | '/tract'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutSiteRoute: typeof AboutSiteRoute
  CharacteristicsRoute: typeof CharacteristicsRoute
  CoatRoute: typeof CoatRoute
  CompositionRoute: typeof CompositionRoute
  ConservationRoute: typeof ConservationRoute
  EditorialRoute: typeof EditorialRoute
  GalleryRoute: typeof GalleryRoute
  GeneticsRoute: typeof GeneticsRoute
  HealthRoute: typeof HealthRoute
  HeatRoute: typeof HeatRoute
  IdentificationRoute: typeof IdentificationRoute
  MilkRoute: typeof MilkRoute
  MorphologyRoute: typeof MorphologyRoute
  NutritionRoute: typeof NutritionRoute
  OriginRoute: typeof OriginRoute
  ReferencesRoute: typeof ReferencesRoute
  ReproductionRoute: typeof ReproductionRoute
  ResearchRoute: typeof ResearchRoute
  TractRoute: typeof TractRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-site': {
      id: '/about-site'
      path: '/about-site'
      fullPath: '/about-site'
      preLoaderRoute: typeof AboutSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characteristics': {
      id: '/characteristics'
      path: '/characteristics'
      fullPath: '/characteristics'
      preLoaderRoute: typeof CharacteristicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coat': {
      id: '/coat'
      path: '/coat'
      fullPath: '/coat'
      preLoaderRoute: typeof CoatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composition': {
      id: '/composition'
      path: '/composition'
      fullPath: '/composition'
      preLoaderRoute: typeof CompositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conservation': {
      id: '/conservation'
      path: '/conservation'
      fullPath: '/conservation'
      preLoaderRoute: typeof ConservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genetics': {
      id: '/genetics'
      path: '/genetics'
      fullPath: '/genetics'
      preLoaderRoute: typeof GeneticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heat': {
      id: '/heat'
      path: '/heat'
      fullPath: '/heat'
      preLoaderRoute: typeof HeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identification': {
      id: '/identification'
      path: '/identification'
      fullPath: '/identification'
      preLoaderRoute: typeof IdentificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milk': {
      id: '/milk'
      path: '/milk'
      fullPath: '/milk'
      preLoaderRoute: typeof MilkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/morphology': {
      id: '/morphology'
      path: '/morphology'
      fullPath: '/morphology'
      preLoaderRoute: typeof MorphologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origin': {
      id: '/origin'
      path: '/origin'
      fullPath: '/origin'
      preLoaderRoute: typeof OriginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reproduction': {
      id: '/reproduction'
      path: '/reproduction'
      fullPath: '/reproduction'
      preLoaderRoute: typeof ReproductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tract': {
      id: '/tract'
      path: '/tract'
      fullPath: '/tract'
      preLoaderRoute: typeof TractRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutSiteRoute: AboutSiteRoute,
  CharacteristicsRoute: CharacteristicsRoute,
  CoatRoute: CoatRoute,
  CompositionRoute: CompositionRoute,
  ConservationRoute: ConservationRoute,
  EditorialRoute: EditorialRoute,
  GalleryRoute: GalleryRoute,
  GeneticsRoute: GeneticsRoute,
  HealthRoute: HealthRoute,
  HeatRoute: HeatRoute,
  IdentificationRoute: IdentificationRoute,
  MilkRoute: MilkRoute,
  MorphologyRoute: MorphologyRoute,
  NutritionRoute: NutritionRoute,
  OriginRoute: OriginRoute,
  ReferencesRoute: ReferencesRoute,
  ReproductionRoute: ReproductionRoute,
  ResearchRoute: ResearchRoute,
  TractRoute: TractRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
